[package]
name = "raytracing-in-one-weekend"
version = "0.1.0"
authors = ["Ari <aricasasn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
rayon = "1.5.0"
png = "0.16.8"